### PR TITLE
Added curate-pkg

### PR DESCRIPTION
**Pull request by andrei-pavel**
Very excited about this one. It's written in bash, it operates on a user-modified JSON configuration which contains:
- apt keys e.g. `https://dl.google.com/linux/linux_signing_key.pub`
- apt repositories e.g. `multiverse`
- apt sources e.g. `deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main`
- apt installs e.g. `google-chrome`
- apt purges e.g. `firefox`
- any custom command package-management-related e.g. `ubuntu-drivers autoinstall`
- ANYTHING `wget`-able e.g. `https://dl.pstmn.io/download/latest/linux?arch=64` (archives or `.deb`)
These are all `apt`-based examples, but it also supports `eopkg` and I would like to continuously add support for other package managers.
The point is to get updates for everything you put in here with just the run of a command and account for each of them only once. What do you think?

### CODE REVIEW

**Comment by agarrharr** [comment]
Thanks for contributing 👍. Since this is a list of awesome cli apps, I don't add every cli app. This cli app is fairly new and doesn't have very many stars, so I won't be merging this PR at this time. And I have to be honest, I'm not sure what `curate-pkg` does. 

I'll leave this PR open for a while to see if it should be added. People can leave a thumbs up on this PR, or star this repo if they think this should be added to the list.

Also, you can subscribe to the [newsletter](https://docs.google.com/forms/d/e/1FAIpQLScrLU51CnfH1vy2em2Rj2aDbiVcIob58mOX5vUJuQsCclRVZA/viewform) to keep up with the latest cli apps and to learn about cli apps.

**Comment by andrei-pavel** [comment]
Here's my motivation. I used to reinstall my OS a lot during the early years of Linux adoption. Whether I was running the bleeding edge version and something just messed up during an upgrade or I deleted an essential file or I `chmod -x`-ed the sudo binary, the easiest fix is sometimes to reinstall the OS - an easy task compared to installing all the apps that you came to love.

That is where it shines. Pull the `config.json` that this app uses (from your github or from the stick you carry around) and run `curate-pkg`. Considering you did configure it once, it does all the work. It installs everything you had before. It purges the bloatware that you didn't want but somehow got installed. 

Assuming Ubuntu, is something available through a `ppa` repository? No problem, it adds the keys, adds the ppa, installs it.

Is something (like `Postman`) not available through a ppa but is `wget`able? No matter the format (`zip`, `tar.gz`, `deb`), it downloads it and installs it. Want to update? No problem, remove the installed directory (`/usr/local/pstmn` - name given by the name of the downloaded file) and run `curate-pkg` again.

Using `AppImages`, `flatpak` or `snap`? Well, this will be supported soon. Should be no problem, they are simpler than `apt`.

I've also added `npm` support, but it's currently in testing.

This also has an `--auto` option to run forever in the background and forget about it.

Hope it makes more sense. Sorry for the long post. I encourage anyone to come with questions or suggestions on this thread.

Thank you! :+1:

**Comment by nico202** [comment]
You should look at nix ;) https://nixos.org/nix/

**Comment by agarrharr** [comment]
@andrei-pavel Makes sense now. I'm in my early years of GNU+Linux adoption right now, and I've started writing [a script to do a similar thing](https://github.com/agarrharr/settings/blob/master/gnu%2Blinux/dotfiles/.config/scripts/install_mine).

I think a little more explanation in your readme about what it is would be helpful, as well as more documentation on how to write your `config. 😃

**Comment by andrei-pavel** [comment]
A minor update, added support for `brew`, `dnf`, `go`, `nix`, `pacaur`, `pacman`, `yaourt`

Chances are that your main package manager is now supported and maybe even some of your secondaries.

I'd definitely recommend giving it a go. Running it is simple, check `curate-pkg -h` for some quick tips.

The simplest use case is adding something in the `installables` array from the json. So after running `curate-pkg`, it should get installed.

**Comment by capaldo** [comment]
Removing old/inactive pull requests.

**Pull request closed without merging**
