### PR TITLE
Add grip

### PR DESCRIPTION
**Pull request by jneidel**
Preview markdown files with exactly the same styles as on github, before committing them locally. For debugging possible formatting errors.

[**repo**](https://github.com/joeyespo/grip)

Install:

```zsh
# pip
$ pip install grip
# homebrew
$ brew install grip
```

### CODE REVIEW

**Comment by jneidel** [comment]
Maybe it could also be sorted under [files](https://github.com/agarrharr/awesome-cli-apps#files), next to doctoc

**Comment by sjclayton** [comment]
> Maybe it could also be sorted under [files](https://github.com/agarrharr/awesome-cli-apps#files), next to doctoc

I was thinking of just placing this in the Development parent category... let me know what you think.

**Comment by jneidel** [comment]
> I was thinking of just placing this in the Development parent category... let me know what you think.

Makes sense!

**Comment by jneidel** [comment]
@sjclayton reopened at #266, with grip moved to development.

**Pull request closed without merging**
