### PR TITLE
Add 'System Interaction Utilities' subcategory

### PR DESCRIPTION
**Pull request by jneidel**
Groups together apps that interact with the system.

### CODE REVIEW

**Comment by capaldo** [comment]
I couldn't see anything mentioning what system battery-cli is for? I'm assuming any Unix system?

**Comment by capaldo** [comment]
I couldn't see anything mentioning what system battery-cli is for? I'm assuming any Unix system?

**Comment by jneidel** [comment]
> I couldn't see anything mentioning what system battery-cli is for? I'm assuming any Unix system?

Unix systems. I tested it and it works, but so does [my own script](https://github.com/jneidel/dotfiles/blob/master/manjaro/scripts/status/battery).

> should we be including these repositories that are not actively maintained or well documented?
> Last and only commit was 2 years ago.

- If it was more complex I'd agree with you. But this is a simple cli, which can be easily replaced with a custom script and is only meant for lazy people :)
- The documentation is short, but complete
- Last commit is 2018 not 2017 (the underlying api, which the cli is only a frontend for)

**Comment by capaldo** [comment]
Makes sense to me and agreed on some people wanting an external/quick solution.

**Pull request merged**
