### PR TITLE
Add create-remote-repo-cli

### PR DESCRIPTION
**Pull request by abhijithvijayan**
#### New App Submission

**App name:** create-remote-repo-cli

**Repo or homepage link:** https://github.com/abhijithvijayan/create-remote-repo-cli

**Description:** Create GitHub repo from Command-line 

**Why you think it's awesome:** One command can automate repository creation on GitHub with user specific repo options. This CLI also can initialize the remote origin to the local project as well.

### CODE REVIEW

**Comment by jneidel** [comment]
I take issue with your wording: "One command can automate...", an interactive tui isn't automation, though it might be more convenient.

If the cli were to take flags and arguments for those interactive prompts it might be more useful (in scripts, etc.).

As it is right now, I personally don't see much use for it, as the interface on par with Githubs, without doing much more.

**Comment by abhijithvijayan** [comment]
Never mind.

**Comment by agarrharr** [comment]
This looks cool! It might not be automation, but it is a cli app. The interface is on par with GitHub's, but it's in the command line. I think that's part of what this list is all about, having more options for doing things in the command line instead of in GUI apps or on the web.

**Comment by abhijithvijayan** [comment]
I closed the PR as I felt it was not worth adding to the list with such criticism to the 'wording' as if it was all about that.

**Comment by jneidel** [comment]
@abhijithvijayan 
Like I said in #370:

> Feel free to argue with me

My criticism above is me trying to understand why this app would be useful, as 1. it isn't useful for me and 2. your 'why is this awesome' didn't convince me.

> Also, this is the 3rd one getting closed in a row.

I didn't close this ticket, you did. You did not engage with me on the last 2 PRs either.

I'm willing to accept these apps, even if they are not for me, if I can see them being useful for others.
But you were unwilling to address my criticism, or even answer me directly.

**Comment by abhijithvijayan** [comment]
#370
- You were talking about the tagline on the demo repo & not the source project repo.
- some of them use the cli & it crossed over *9,000* downloads so far.
- the purpose of the cli is to sort the github stars to a single list instead of going through literally every page(on GitHub) with ~20 results max.


I am closing this as well. It violates the contributing guidelines.

**Pull request closed without merging**
