### PR TITLE
Add "Advanced New File"

### PR DESCRIPTION
**Pull request by tanrax**
Fast creation of files and directories. Mimics the operation of AdvancedNewFile (Vim plugin)

#### New App Submission

**App name:** Advanced New File

**Repo or homepage link:** https://github.com/tanrax/terminal-AdvancedNewFile

**Description:** Fast creation of files and directories. Mimics the operation of AdvancedNewFile (Vim plugin) 

**Why you think it's awesome:**

### CODE REVIEW

**Comment by jneidel** [comment]
**Why you think it's awesome**?

**Comment by tanrax** [comment]
It's a time-saving tool for creating new folders and files, and you can create multiple folders and files simultaneously. It's essential in my daily life.

**Comment by jneidel** [comment]
It's a glorified `mkdir -p` in my book.
Creating files is a waste of time, just create them when you open them (e.g. `vim new-file` and then write the file).

**Comment by tanrax** [comment]
We all use Vim! :)

**Pull request closed without merging**
