### PR TITLE
Add hsimp-cli

### PR DESCRIPTION
**Pull request by zacanger**
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).

**Repo or homepage link:**

https://github.com/zacanger/hsimp-cli

**Description:**

Password complexity/crackability checker using <https://howsecureismypassword.net/>'s libraries (no network calls).

**Why you think it's awesome:**

Provides a nice CLI interface to HSIMP without needing to submit a password over the network

### CODE REVIEW

**Comment by jneidel** [comment]
Why would you need this?

Passwords should be generated randomly at sufficient length by your password manager anyway.

**Comment by zacanger** [comment]
I agree, but less than 25% of people surveyed in the US use password managers. That percentage is probably higher for developers, but in my experience password manager use isn't anywhere near as common as it should be even in engineering.

**Comment by jneidel** [comment]
Sure, but those 75% of people won't bother checking their password for complexibility either. Because if they cared about it, they would be using a password manager.

**Comment by zacanger** [comment]
Depressing, but fair point. I'm going to close this

**Pull request closed without merging**
