### PR TITLE
Add SimpleLocalize

### PR DESCRIPTION
**Pull request by jpomykala**
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).

**Repo or homepage link:**
https://github.com/simplelocalize/simplelocalize-cli

**Description:**
Open source tool for managing i18n keys in software projects.

**Why you think it's awesome:**
It's open source, does not need NodeJS, Java or Docker installed. It's native and it helps in software development. I'm not wasting my time on handling i18n keys in application. I'm just invoking this CLI and all my translation keys are extracted or uploaded to TMS.

### CODE REVIEW

**Comment by jneidel** [comment]
> Open source tool for managing i18n keys in software projects.

I object. The cli itself does not manage the i18n keys, the SaaS app behind it does. And that one isn't open source.

It's like adding my [vpn (mullvad)](https://github.com/mullvad/mullvadvpn-app), which is technically a cli, but is in actuality useless without the backend behind it (which I am paying for).

I know the same could be said for [google-drive-upload](https://github.com/labbots/google-drive-upload), but I feel that that one add value by doing stuff the normal cli/other gdrive interface aren't doing.
It goes beyong being a mere front for the paid backend service.

I think this would be more suited for a list of web services, like the mullvad cli would be more suited to a list of vpns.

@jpomykala feel free to discuss.

**Comment by jpomykala** [comment]
@jneidel Hey, service is free, and CLI is open source (checkout the repository link). The CLI can show you which translation keys are not used in the code and validate the project :)

image

**Comment by jneidel** [comment]
> service is free

Having a free tier != free.

> and CLI is open source (checkout the repository link)

I know. I never said it wasn't. It's the service behind it being non-free that is the problem.

> The CLI can show you which translation keys are not used in the code and validate the project

I doubt this is useful for use outside of also using the SaaS.
And it's not what you described as awesome before:

> I'm not wasting my time on handling i18n keys in application. I'm just invoking this CLI and all my translation keys are extracted or uploaded to TMS.

What you're describing here is the service, not the cli. As the cli is just an empty shell for the service, like I said before.

**Comment by jpomykala** [comment]
@jneidel 

- aws-cli (free tier), 
- azure-cli (free tier), 
- github-cli (free tier),  

Screenshot 2021-02-19 at 21 54 49

- terjira (free tier)

Screenshot 2021-02-19 at 21 55 56

- google-drive-upload (free tier)

Screenshot 2021-02-19 at 21 54 33

and they are just empty shells with free tiers. In the exactly same schema my CLI works.

**Comment by jpomykala** [comment]
@jneidel 
How about this one?
https://github.com/dnote/dnote
https://www.getdnote.com/pricing/

**Comment by jneidel** [comment]
>> https://github.com/dnote/dnote

> It also offers a seamless multi-device sync.

Can be used w/o service behind it.

>> google-drive-upload

I explained it above. Same applies to terjira

>> github-cli

Fully usable w/o paying. I could get a student account but why bother, the free/standard version does everything.

>> aws-cli, azure-cli

[Removed](https://github.com/agarrharr/awesome-cli-apps/commit/4f082c4e6b77cc019b8ec6489d6b20a5b8a48665)

**Comment by jpomykala** [comment]
My CLI is also usable with free accounts. Did you check it? It offers the same functionality for free and paid accounts. It fully available to everyone, open-source and it gives additional benefits if it’s used with the service.

**Pull request closed without merging**
