### PR TITLE
Add qotm

### PR DESCRIPTION
**Pull request by WessCoby**
#### New App Submission

**App name:** qotm

**Repo or homepage link:** https://github.com/WessCoby/qotm

**Description:** It outputs random tech or programming quotes (with author)

**Why you think it's awesome:** Most tech-related quotes offer some form of advice (or tips), inspiration or motivation. Hence, `qotm` seeks to serve that purpose - bringing a random tip or inspirational message to the user in just a moment.

### CODE REVIEW

**Comment by jneidel** [comment]
Hey @WessCoby,
I don't think I'm gonna merge this app at this time, as it still is fairly new, small (~85 quotes are exhausted faster than you think), and extremely basic (no --help page, can be replicated in no more than 10 lines of shell script, etc.).

**Comment by WessCoby** [comment]
Oh ok. Thanks for the feedback. I'll work on it.
So i can resubmit in say a month or 2 right?

**Comment by jneidel** [comment]
> So i can resubmit in say a month or 2 right?

Just comment on this issue and I'll check it out.

**Comment by WessCoby** [comment]
Ok. Thanks

**Pull request closed without merging**
