### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by caminsha**
Fixed The typo in section web dev

#### New App Submission

**App name:**

**Repo or homepage link:**

**Description:**

**Why you think it's awesome:**

### CODE REVIEW

**Comment by jneidel** [comment]
@caminsha, it refers to [bower](https://bower.io) and is thus correct.

**Comment by caminsha** [comment]
I'm sorry I didn't get it.. 
Sorry for the additinional work... :/

**Comment by caminsha** [comment]
Maybe a link would have been helpful.. Or don't you want to make links in your description? I'd understand both ways..

**Comment by jneidel** [comment]
@caminsha, no problem. Thanks for trying to partake!

> Maybe a link would have been helpful

The repo points to bowers website :)

**Comment by caminsha** [comment]
True. I'm sorry. I really need to sleep.
Btw: Very nice repo, thanks!

**Pull request closed without merging**
