### PR TITLE
Add app - ricksay

### PR DESCRIPTION
**Pull request by roma-guru**
#### New App Submission

- [✔︎] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).

**Repo or homepage link:**
https://github.com/roma-guru/ricksay

**Description:**
Rick & Morty quotes of the day with ponies included!

**Why you think it's awesome:**
Rick and Morty is quite popular among geeks like us.

### CODE REVIEW

**Comment by jneidel** [comment]
@roma-guru Why are the quotes all in different files?
It'd be much cleaner (fs and code) if they were all in one.

**Comment by roma-guru** [comment]
Thanks for comment. Do you mean fortune-like file format?
So it can be usable outside of ricksay. I will refactor it tomorrow.

**Comment by jneidel** [comment]
Having a single text file with the quotes:

```txt
Rick: Wubba Lubba Dub Dub!
Rick: [whispers] Jubbajubbajubbajubba?
etc.
```

instead of all the different files, makes it even easier for outside use.
But its not that big a deal, since creating that file is only a `cat *` away.

**Comment by roma-guru** [comment]
Fixed in the new release.
I’ve used fortune format with percent delimiters, because quotes may be multiline potentially.
Thanks.

**Pull request merged**
