### PR TITLE
Add minisign

### PR DESCRIPTION
**Pull request by SaphireLattice**
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md#readme).

**Repo or homepage link:** https://github.com/jedisct1/minisign

**Description:** "A dead simple tool to sign files and verify digital signatures."

**Why I think it's awesome:** It's an app that does only a single thing and does it well, while also providing alternative to the sprawling popular option of GPG for signing.

### CODE REVIEW

**Comment by jneidel** [comment]
Is it compatible with GPG?

> providing alternative [..] to GPG

In practice that sound like I will need both of them when people start using this. [relevant xkcd](https://xkcd.com/927/)

> A dead simple tool to sign files and verify digital signatures

I don't know what so bad about:

```sh
gpg --sign test
gpg --verify test.gpg
```

**Comment by SaphireLattice** [comment]
No, it is not compatible with GPG. I felt that the tool could be compared to GPG in that regard as it was the only other standalone (as standalone as GPG can be, that is) thing that did signing and/or verifying.

> In practice that sound like I will need both of them when people start using this. relevant xkcd

I do not really know what to comment on this or what is required from me here? It's nothing I can affect, and denying inclusion of a tool on grounds of it being something different but in similar niche to a popular one sounds rather strange. Assuming that's what this comment is about? I am confused about what it meant to convey ^^'

The "dead simple" description is one that is used in at least one distributive packaging system, and is what the tool self-describes as.

As for GPG, it is rather massive system that can be a lot of things that are barely related to one another, and it has an enormous identity management layer. Whereas this tool does only one thing, and focuses only on it. The contribution guide even says that `... suggested software should ... do one thing and do it well, ...`

**Comment by SaphireLattice** [comment]
By the way [SSH can sign stuff](https://www.man7.org/linux/man-pages/man1/ssh-keygen.1.html) (`ssh-keygen -Y sign` and `-Y verify`) too, and can be used for signing git commits.

GPG is... not that necessary these days outside of email? Too bad SSL S/MIME certs are either a scam or org-only

**Comment by jneidel** [comment]
> denying inclusion of a tool

I'm not denying it, I'm trying to understand it's purpose by comparing it to a tool I understand (GPG.)

> As for GPG, it is rather massive system that can be a lot of things that are barely related to one another, and it has an enormous identity management layer. **Whereas this tool does only one thing, and focuses only on it.**

This sounds like a good differentiator to me 😄

**Comment by SaphireLattice** [comment]
Sorry about this, was cleaning my PRs and guess acted a bit rash here.

Would you like me to reopen and prep this up for merging again?

Other security apps of note I can think of adding, though likely separately, are:
- Sequoia - alternative PGP tool, with *optional* drop-in GPG replacement. It’s another “Swiss army knife” tool, but everything is split into well defined subcommands. Honestly reminds me of Windows certificate management tool.
- age - encryption utility that operates with explicitly passed to it keys. It can encrypt and decrypt. That’s it. Someone made a `pass` variant for it though! And a rust version `rage`
- Probably would be good to note a few words about SSH signing? This isn’t exactly a “new separate program” but it’s not a very well known capability.

**Comment by jneidel** [comment]
Feel free to add these (along with GPG, which isn't on the list either.)

You can create a new section "Encryption" for it.

Having them all in the same PR would also be fine for me :+1:

**Pull request closed without merging**
