### PR TITLE
Add shell-velocity

### PR DESCRIPTION
**Pull request by saccarosium**
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md#readme).

**Repo or homepage link:** <https://github.com/saccarosium/shell-velocity>

**Description:**  A portable notational velocity for your shell written in POSIX shell.

> **Warning**
> I've made the application, so I'm biased.

**Why I think it's awesome:** Because is a complitly portable note taking solution that: unite the search and creation of file in one step, let's you customize his interface and works with wathever plaintext file formats you want.

### CODE REVIEW

**Comment by jneidel** [comment]
` A portable notational velocity` is a bad way to describe your app. Nobody will get from that tag line what the app is about.
I guess this in in reference to [Notational_Velocity](https://en.wikipedia.org/wiki/Notational_Velocity)?

> Notational Velocity hasn't seen any development activity since September 2011.

I don't know why you would hitch your wagon to that :smile:

**Comment by jneidel** [comment]
As per contrib guidelines I'll have to close this for now (90 days rule).

But feel free to comment here to ask me to reopen.

**Comment by jneidel** [comment]
Also the the issues and PR I opened in the project.

**Comment by saccarosium** [comment]
> As per contrib guidelines I'll have to close this for now (90 days rule).

Fare enough I will wait for reopen

> I guess this in in reference to [Notational_Velocity](https://en.wikipedia.org/wiki/Notational_Velocity)?
>
> Notational Velocity hasn't seen any development activity since September 2011.
> I don't know why you would hitch your wagon to that 😄

The original [Notational Velocity](https://notational.net/) and his philosophy is the main inspiration for the program. Basecly the entire UX of the program mimics his. It's just a way for me to omage the original developer.

**Pull request closed without merging**
