### PR TITLE
add import-github-labels-cli

### PR DESCRIPTION
**Pull request by abhijithvijayan**
#### New App Submission

**App name:** import-github-labels-cli

**Repo or homepage link:** https://github.com/abhijithvijayan/import-github-labels-cli

**Description:** CLI to import labels from another repository on GitHub 

**Why you think it's awesome:** Sometimes when a user needs to import / manage GitHub labels used in one project to another in a single command, this CLI does it neat & perfect.

### CODE REVIEW

**Comment by jneidel** [comment]
In violation of the [contrib guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).

Please submit again at a later time.

**Comment by abhijithvijayan** [comment]
No need.

**Comment by agarrharr** [comment]
Cool! This looks really useful if you always use the same labels on each repository or if you want to copy the labels from another project. I'm going to set a reminder to check back on this when the project is 90 days old.

**Comment by abhijithvijayan** [comment]
I didn't close it. So.

**Comment by agarrharr** [comment]
@jneidel This PR looks good to me.

**Pull request merged**
