### PR TITLE
Added RTV, an interface to view and interact with reddit from your te…

### PR DESCRIPTION
**Pull request by hervehobbes**
Added RTV:
RTV provides an interface to view and interact with reddit from your terminal

### CODE REVIEW

**Comment by hervethouzard** [comment]
Added RTV, Weechat, Terminal velocity and Dwarf

**Comment by aharris88** [comment]
These look interesting. I'll look into them later. Thanks.

**Comment by laughedelic** [comment]
As a watcher of this repo, I think pull-requests should contain one addition. It's easier to see check the updates of the list then.

**Comment by aharris88** [comment]
I agree. Also, we shouldn't have a new category for only one cli app. @hervethouzard Can you open individual PRs for these?

**Comment by laughedelic** [comment]
I think there's no point in opening new pull-requests for these apps if this pr can be merged. 

I was going to say that this should be just mentioned in the `contributing.md`, but now I see that it's already there:

> - Make an individual pull request for each suggestion

Probably a pull-request template would be also helpful for this?

**Comment by hervethouzard** [comment]
@aharris88,

Open a new PR for 4 lines ... ? Seriously ?
Ignore, reject, them.

**Comment by aharris88** [comment]
@hervethouzard You don't have to, it just makes it easier. Thanks for contributing! 👍

**Comment by agarrharr** [comment]
I've been busy IRL lately, Sorry about that. I finally got around to this and I added all of these apps in separate commits. Thanks for the contribution @hervehobbes.

**Pull request closed without merging**
