### PR TITLE
Add productivity CLI tool eureka

### PR DESCRIPTION
**Pull request by simeg**
I think this tool that I wrote called [eureka](https://github.com/simeg/eureka) would be a good fit in this list. It fits in the _Productivity_ section because with the tool you can store your ideas without leaving the terminal, hence increasing your productivity (assuming you work a lot in the terminal).

### CODE REVIEW

**Comment by agarrharr** [comment]
Looks cool, I'll check it out! 👍

**Comment by agarrharr** [comment]
Reminds me of something I made: [thoughts-cli](https://github.com/agarrharr/thoughts-cli/).

**Comment by simeg** [comment]
Hey @agarrharr. Yeah, they have the same purpose. I actually looked at your tool . The main difference is that `eureka` stores your idea/thought on Github as part of when you input it. So you won't lose it if your HDD crashes 🔥.

What do you think about adding it to the list? 😃

**Comment by simeg** [comment]
Ping here too :) @agarrharr

**Comment by jamesgeorge007** [comment]
@simeg Update your remote branch :+1:

**Comment by simeg** [comment]
@jamesgeorge007 Done!

**Comment by jamesgeorge007** [comment]
@simeg I would love to know your thoughts on [Mevn-CLI](https://github.com/madlabsinc/mevn-cli) and [teachcode](https://github.com/madlabsinc/teachcode)

**Pull request merged**
