### PR TITLE
Add lf

### PR DESCRIPTION
**Pull request by JurisMajors**
#### New App Submission

**App name:**
LF (list files)
**Repo or homepage link:**
https://github.com/gokcehan/lf

**Description:**
Fast file browser, using Server-Client architecture, developed with focus on extensive customizability (mostly with bash scripts).
**Why you think it's awesome:**
It is extremely customizable since you can inject bash scripts nearly everywhere and also define custom commands with that. The development process always considers whether the user could easily change or alter the new functionality if he wanted to.
It is fast and efficient (written in Go)
Uses a server-client architecture where clients are the instances of the file manager (so file selections are shared between the instances etc.) which is an original and useful approach for a file managers architecture.

### CODE REVIEW

**Comment by jneidel** [comment]
Hey @HumanJBooF,
do you want to take this PR?

My process for checking PRs:
- Check if the repo is too young (incomplete) or if it's no longer maintained (outdated)
- Install the program
- Gauge it's usefulness, while considering what the submitter wrote about it
- Check if the PR conforms to the contribution guidelines (not added at the end of the category, wrong category, wrong format, etc.)
- (Optional: Cleanup app description to remove marketing bs:grin:)

Can you @ me before you merging?

**Comment by jneidel** [comment]
> Seems to work

What does that mean? Have you tried it? 

> has good amount of stars.

That makes it more relevant, but in itself should not be a reason

Do you want to try the description cleanup? The current one is too long/can be reduced a more relevant message.

**Comment by capaldo** [comment]
> > Seems to work
> 
> What does that mean? Have you tried it?
> 
> > has good amount of stars.
> 
> That makes it more relevant, but in itself should not be a reason
> 
> Do you want to try the description cleanup? The current one is too long/can be reduced a more relevant message.

I use LF so I can vouch for its utility/usefulness/stability etc.

**Comment by HumanJBooF** [comment]
My bad I should have elaborated more and next time I for sure will.

**Pull request merged**
