### PR TITLE
Add fjira.

### PR DESCRIPTION
**Pull request by mk-5**
#### New App Submission

- [X] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md#readme).

**Repo or homepage link:**

https://github.com/mk-5/fjira

**Description:**

Fjira is a terminal user interface for Jira. It provides a fuzzy-search approach to interact with Jira tickets. Its key features are:

- Exploration of Jira Projects and Issues
- Quick modification of Jira Issue assignees
- Quick modification of Jira Issue statuses
- Easy commenting on Jira tickets
- Ability to manage multiple workspaces (Jira URLs)
- Jira Issue search using custom JQL expressions

**Why I think it's awesome:**

You can do your daily Jira stuff directly from your terminal - that's awesome 😄 

And let's be real, haven't we all been there? Navigating between Jira tickets in a browser, it can get pretty frustrating. With Fjira, that hassle is history.

### CODE REVIEW

**Comment by jneidel** [comment]
Hi,
how does it compare to:
- https://github.com/go-jira/jira
- https://github.com/ankitpokhrel/jira-cli

**Comment by jneidel** [comment]
I created an AUR package, see: https://github.com/jneidel/fjira/pull/1

**Comment by mk-5** [comment]
> Hi, how does it compare to:
> 
> * https://github.com/go-jira/jira
> * https://github.com/ankitpokhrel/jira-cli

The first one - as I see it's not TUI app, so it doesn't have terminal user interface.
The second one - I've never seen it, it looks really nice as well. Pretty similar to fjira - but it looks a bit more complex. I found really handy to use fjira because it gives an interface kind of fzf-ish. Changing status in Jira ticket takes ~2-5 seconds - if you are familiar with the app. That was my main intention for fjira.. to reduce time needed for jumping between Jira web-browser interface.

**Comment by jneidel** [comment]
It might be helpful to add a little explainer like that to the readme so people can compare and know what they're getting into.
(Inspired by this: https://github.com/mgunyho/tere#similar-projects)

**Comment by jneidel** [comment]
Another one:
- ttps://github.com/keepcosmos/terjira

**Pull request merged**
