### PR TITLE
Add translate-shell

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**
**Why you think it's awesome:**

I always install it to all my machines. I love the author for good sense of style.

### CODE REVIEW

**Comment by jneidel** [comment]
Please read the contribution guidelines.

**Comment by vitaly-zdanevich** [comment]
> Please read the contribution guidelines.

Fixed formatting.

**Comment by jneidel** [comment]
> > Please read the contribution guidelines.
>
> Fixed formatting.

No you haven''t :smile: 
Did you **actually** read the guidelines?

**Comment by vitaly-zdanevich** [comment]
Yes I read. If you accept this software to your list - I need to add it to the end of category?

**Comment by jneidel** [comment]
> I need to add it to the end of category?

That is what I was referring to. Why didn't you fix this your self if you knew?

**Comment by vitaly-zdanevich** [comment]
Sorry, I thought that siblings (logic grouping) is more important :(

**Comment by jneidel** [comment]
It's **also** important.

**Pull request merged**
