### PR TITLE
Add xiringuito - SSH-based "VPN for poors"

### PR DESCRIPTION
**Pull request by ivanilves**
This adds xiringuito - SSH-based "VPN for poors"

Thanks!

### CODE REVIEW

**Comment by agarrharr** [comment]
Thanks for contributing! Can you explain why xiringuito is awesome? I'm not super familiar with this type of thing. And what does "VPN for poors" mean? Does it mean "[A poor man's](https://idioms.thefreedictionary.com/a+poor+man's) VPN"?

**Comment by ivanilves** [comment]
_I'm sorry I haven't told the main thing - WHY? :innocent:_ 

Yes. It's poor's man VPN, but not it terms it is bad, rather than you do not need to set up a VPN server and you will get slower-than-the-real-VPN performance with it. It is mostly for sysadmins reaching a closed infrastructure behind the firewall/bastion host to debug/fix things **fast and without a hassle**. It has a special support for AWS VPCs (VPN route discovery), but it is not limited to AWS and works everywhere.

Aso, `xiringuito` is awesome, because:
* easy to install (no dependencies, no configurations)
* allows you to manage one, few or many connections easily (and connect em simultaneously if you want)
* it has `xaval` connection manager - a tool that may record and later re-use your connection profiles
* though you are free to use or not to use `xaval` connection manager - people also use `xiringuito` for ad-hoc onetime connections
* Just look at this GIF :wink:

**Comment by agarrharr** [comment]
I changed the description. Does that make sense to you? Is it correct? I put quotes around VPN because it looks like it's not actually a vpn, but it acts like one.

**Comment by ivanilves** [comment]
Yeah! It's true so it's OK! :+1:

**Pull request merged**
