### PR TITLE
Add dark-mode

### PR DESCRIPTION
**Pull request by capaldo**
#### New App Submission

**App name:** dark-mode

**Repo or homepage link:** https://github.com/sindresorhus/dark-mode

**Description:** Toggle macOS's dark mode from the terminal.

### CODE REVIEW

**Comment by jneidel** [comment]
Please change the description from `Toggle macOS's dark mode from the terminal.` to `Toggle dark mode.`.

Reasoning:
- its in the macos section, macos can be omitted from the description
- its on a cli-apps list, `xxx from the terminal` is unnecessary

**Comment by capaldo** [comment]
> Please change the description from `Toggle macOS's dark mode from the terminal.` to `Toggle dark mode.`.
> 
> Reasoning:
> 
> * its in the macos section, macos can be omitted from the description
> * its on a cli-apps list, `xxx from the terminal` is unnecessary

I've updated the dark-mode description as you've outlined.

**Comment by jneidel** [comment]
> updated dark-mode description 

Is not a good commit message. Better would be for example: `Update dark-mode description` or in the context of this PR you can just use `Update description`.

For a good reference on [writing commit messages](https://chris.beams.io/posts/git-commit/).

**Comment by capaldo** [comment]
> > updated dark-mode description
> 
> Is not a good commit message. Better would be for example: `Update dark-mode description` or in the context of this PR you can just use `Update description`.
> 
> For a good reference on [writing commit messages](https://chris.beams.io/posts/git-commit/).

I did in fact read this prior to contributing again but forgot to not use the non-imperative form. Thanks for pointing that one out again to me.

**Comment by jneidel** [comment]
Capitalization as well :smile:

**Pull request merged**
