### PR TITLE
Add Discharge

### PR DESCRIPTION
**Pull request by brandonweiss**
[Discharge](https://github.com/brandonweiss/discharge) is, as far as I’m aware, the easiest way to deploy static websites to Amazon S3. It can also configure an SSL certificate and distribute the site via CloudFront, all without having to know anything about AWS. I spent hours poring over AWS’s terrible docs so no one else would have to. There is also a prompt-based UI to help you configure it. And it’s very well documented.

Thanks for considering!

### CODE REVIEW

**Comment by brandonweiss** [comment]
@agarrharr Have you had a chance to look at this yet? Thanks! 🙏

**Comment by jamesgeorge007** [comment]
@brandonweiss Resolve conflicts

**Comment by jamesgeorge007** [comment]
@brandonweiss Update your remote branch :+1:

**Comment by brandonweiss** [comment]
@jamesgeorge007 Done!

**Comment by jamesgeorge007** [comment]
@brandonweiss I would love to know your thoughts on [Mevn-CLI](https://github.com/madlabsinc/mevn-cli) and [teachcode](https://github.com/madlabsinc/teachcode)

**Comment by brandonweiss** [comment]
@jamesgeorge007 👍🏼 I’ll email you!

**Pull request merged**
