### PR TITLE
added emoji-search to the list

### PR DESCRIPTION
**Pull request by keshav11**
Emoji-search is a command line tool that can be used to search emojis.

link: https://github.com/keshav11/emoji-search

### CODE REVIEW

**Comment by jneidel** [comment]
Could be grouped into a new subcategory **Emoji** together with:
- emoj
- emoji-finder

**Comment by sjclayton** [comment]
@jneidel Where would you put the new subcategory??

Just under **Other**?

**Comment by sjclayton** [comment]
First of all, thanks for contributing :+1:. Since this is a list of awesome cli apps, We can't add every cli app. This cli app is fairly new and doesn't have many stars as of yet, so we won't be merging this PR at this time.

I'll leave this PR open for a while to see if it should be added at a later time. People can leave a thumbs up on this PR, or star the repo if they think this should be added to the list.

**Comment by jneidel** [comment]
> @jneidel Where would you put the new subcategory??
> Just under **Other**?

@sjclayton It doesn't really fit anywhere else, **Text Manipulation** or **Utilities** maybe being the closest to it.

Maybe we could open a **Writing** category of sort, where this would fit in as well.

**Comment by jneidel** [comment]
Closing in accordance with #320

**Pull request closed without merging**
