### PR TITLE
Add json-dotenv

### PR DESCRIPTION
**Pull request by decryptus**
#### New App Submission

**App name:**
json-dotenv
**Repo or homepage link:**
https://github.com/decryptus/json-dotenv
**Description:**
Manipulate and extract envfiles in json format.
**Why you think it's awesome:**

### CODE REVIEW

**Comment by decryptus** [comment]
New App Submission
App name: json-dotenv

Repo or homepage link https://github.com/decryptus/json-dotenv:

Description: https://github.com/decryptus/json-dotenv

Why you think it's awesome:

**Comment by jneidel** [comment]
[Can't install the app for testing](https://github.com/decryptus/json-dotenv/issues/1) and has repo zero stars.

**Comment by decryptus** [comment]
Hi @jneidel,

You right, I forget to upload for python3, it's done now.

It's an obligation to have a star?

Best regards.

**Comment by jneidel** [comment]
> It's an obligation to have a star?

No, it's to ensure that there is interest in the product.

**Comment by decryptus** [comment]
Hi @jneidel,
thx for the answer.
I will wait to collect some stars, but it's difficult to have stars if I can't promote it, because I have no star. ;)

Best regards.

**Pull request closed without merging**
