### PR TITLE
Added google drive upload to Productivity

### PR DESCRIPTION
**Pull request by labbots**
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).

**Repo or homepage link:** 
https://github.com/labbots/google-drive-upload

**Description:**
Google Drive Upload (gupload) is a  cli tool that enables users to upload files and folders to google drive from command line. It also has ability to upload files in parallel and resume interrupted uploads.

**Why you think it's awesome:**
It allows users to upload files and folders to the user's google drive from command line. The script can also be used as part of CI to push artifacts into google drive and share it with anyone.

### CODE REVIEW

**Comment by jneidel** [comment]
Why use this over rclone?

**Comment by labbots** [comment]
This is a lightweight pure bash based script that allows users to upload to Google drive. It does not depend on external libraries other than what comes with standard Linux os. The script could parallel upload files and resume interrupted uploads.

**Comment by labbots** [comment]
@jneidel any thoughts on the PR?

**Comment by Akianonymus** [comment]
@jneidel well, for starters, it can upload folders along with subfolders preserving the folder hierarchy.

Last i checked, rclone doesn't support that.

**Comment by Akianonymus** [comment]
New update: The script can run on any posix compatible shell environment, so pretty much all unix and linux systems.

**Pull request merged**
