### PR TITLE
Add dnote

### PR DESCRIPTION
**Pull request by sungwoncho**
#### New App Submission

**App name:** dnote

**Repo or homepage link:** https://github.com/dnote/dnote

**Description:** Dnote is a simple and end-to-end encrypted note-taking software inside a terminal.

**Why you think it's awesome:** It is encrypted and therefore respects user privacy. It is free and open source software under GPLv3. The server is also free and open source under AGPLv3 and self-hostable.

### CODE REVIEW

**Comment by jneidel** [comment]
> It is encrypted and therefore respects user privacy. It is free and open source software under GPLv3. The server is also free and open source under AGPLv3 and self-hostable.

That makes it awesome, but none of that is your opinion, it's just facts :)

@sungwocho so why do **you** think it's awesome?

**Comment by jneidel** [comment]
Oh, looked at the pricing and all the features that make it unique are behind the paywall (normal users are not gonna setup their own server).

**Comment by sungwoncho** [comment]
@jneidel I could not find anything against paid offerings in the [contribution guide](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md). However, I respect your decision since you are a collaborator.

At the same time, I would like to request that this PR be reopened. The reason is that CLI can be easily downloaded and used free of charge as a standalone software running offline. In fact, that is how many people are using it ([example 1](https://www.softpedia.com/get/Programming/Other-Programming-Files/Dnote-CLI.shtml), [example 2](https://github.com/dnote/dnote/issues/90#issuecomment-417945736)). The server side software simply exists to provide sync and web editor feature. Everything including the server side is free and open source.

@agarrharr how do you feel about it?

**Comment by jneidel** [comment]
> agarrharr how do you feel about it?

agarrhaar is not actively partaking anymore, no need to tag him.

> he reason is that CLI can be easily downloaded and used free of charge as a standalone 
software running offline. In fact, that is how many people are using it

Then why did you not say anything about that but focused on E2E, privacy, AGPL, self-hostable in your opinion on the software.

Your proposed descriptions, almost, solely about the merits that the server adds to the app: 

> A simple, end-to-end encrypted notebook that resprects user privacy.

You framed the conversation this way, that why I rejected the addition on those grounds.

**Comment by jneidel** [comment]
That makes [this comment](https://github.com/agarrharr/awesome-cli-apps/pull/357#issuecomment-520139263) relevant again.

**Comment by jneidel** [comment]
And I hope you see how this contradicts each other:

> However, I respect your decision since you are a collaborator.

> agarrharr how do you feel about it?

**Comment by sungwoncho** [comment]
@jneidel Sorry, I have missed the following comment:

> @sungwoncho so why do you think it's awesome?

As an author, I think this software is awesome in that it provides a privacy focused and free alternative to proprietary note-taking applications right inside the terminal.

> And I hope you see how this contradicts each other:

Not at all. I think one can respect another's opinion, stay civilized but can still disagree.

**Comment by jneidel** [comment]
> >  And I hope you see how this contradicts each other

> Not at all. I think one can respect another's opinion, stay civilized but can still disagree.

But you were not talking about my opinion, but my decision (`I respect your decision`), i.e. me closing the issue, which you disagreed with later on in that comment. And then you tried to go over my head.
I'm not angry or anything, I just want to point out how this looks from my perspective (not good :smile:).

**Comment by jneidel** [comment]
> I think this software is awesome in that it provides a privacy focused and free alternative to proprietary note-taking applications right inside the terminal.

vim? Private, OSS, terminal. [There are plugins that make vim less distracting](https://github.com/junegunn/goyo.vim).

How does this app benefit me, who is doing all of my notes in vim with a directory of md files?

**Comment by jneidel** [comment]
And yes, this questioning goes well beyond the scope of normal submissions, I'm just curious to see how this compares to my current workflow.

**Comment by sungwoncho** [comment]
> And then you tried to go over my head.

I see where you are coming from. I apologize.

> How does this app benefit me, who is doing all of my notes in vim with a directory of md files?

This tool might be able to add more benefit to the purely vim-based workflow by:

* offering full text search `dnote find [your keyword]`
* making your data portable since it stores data in a single SQLite file.

On the other hand, vim-based workflow has an advantage in that it can store notes in an arbitrary directory structure, possibly deeply nested to represent complex hierarchy.

**Comment by jneidel** [comment]
> offering full text search `dnote find [your keyword]`

I have an equivalent alias:

```
$ n <keyword> *.md
matches...

$ whence in
grep --line-number --with-filename --no-messages --recursive --exclude-dir=node_modules
```

> making your data portable since it stores data in a single SQLite file.

My notes are a git repo :)

But I see how this can be useful for somebody that hasn't or doesn't want to spend a lot of time on their setup :smile:

**Comment by sungwoncho** [comment]
I see, thanks for the feedback and updating the description.

**Pull request merged**
