### PR TITLE
Add "is-wordpress"

### PR DESCRIPTION
**Pull request by tanrax**
Checks if a Website is made in WordPress

#### New App Submission

**App name:** is-wordpress

**Repo or homepage link:** https://github.com/tanrax/is-wordpress

**Description:** Checks if a Website is made in WordPress 

**Why you think it's awesome:**

### CODE REVIEW

**Comment by jneidel** [comment]
From the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md):

`The apps repository is older than 90 days.`

Closes #381 as it applies to that repo as well.

**Comment by tanrax** [comment]
The software is from 2017, it has been migrated to Github very recently (its apparent early age).

**Comment by jneidel** [comment]
Okay, then yet again: **Why you think it's awesome**?

**Comment by jneidel** [comment]
If you want people to do something for you (look at your programm, add it to this list) you could at least bother to:
1. read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md) (there is another violation apart from the age)
2. do what the people that you want something from ask of you (without direct inquiry)

**Comment by tanrax** [comment]
> Okay, then yet again: **Why you think it's awesome**?

Because mkdir can't do it and there's nothing like it :)

**Pull request closed without merging**
