### PR TITLE
visidata -  A spreadsheet multitool for exploring/changing data

### PR DESCRIPTION
**Pull request by frosencrantz**
visidata - A spreadsheet multitool for exploring and arranging data (csv/json/xml/xls/yaml/etc)

#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md).

**Repo or homepage link:**
https://github.com/saulpw/visidata

**Description:**
 A spreadsheet multitool for exploring and arranging data (csv/json/xml/xls/yaml/etc)

**Why you think it's awesome:**
It makes exploring and modifying data (csv, json, yaml, html tables) very easy.  It is very responsive and makes it easy to filter data.

### CODE REVIEW

**Comment by frosencrantz** [comment]
Hi @jneidel this PR is older than another one that you've been merged in. Is there something else that I need to do for this request?

**Comment by frosencrantz** [comment]
Hello @jneidel or @agarrharr  what more do I need to do to have this PR committed?  We are approaching a year since the request was first made.

**Comment by jneidel** [comment]
I'll take a look at it when I got some time.

**Comment by jneidel** [comment]
Looks great. You should've linked to the [demo](https://www.youtube.com/watch?v=N1CBDTgGtOU) as well :)

**Pull request merged**
