### PR TITLE
Add termbin

### PR DESCRIPTION
**Pull request by sjclayton**
#### New App Submission

**App name:**
termbin

**Repo or homepage link:**
https://termbin.com

**Description:**
Command line pastebin for sharing terminal output.

**Why you think it's awesome:**
Using netcat - which is widely available, it allows you to quickly send terminal output to a pastebin-like service.

### CODE REVIEW

**Comment by jneidel** [comment]
Not really a cli or an app, but a service.
I like it nonetheless.

**Comment by sjclayton** [comment]
@jneidel I didn't realize it until further investigation that it is only a service based on this

https://github.com/solusipse/fiche

Ideally we shouldn't add it, because it isn't a cli / app... Do you think we should?

**Comment by jneidel** [comment]
Like I said I like it, but it does not meet the repos requirements.

**Comment by xrat** [comment]
I think there should be an **awesome list of 1liners** :-)

**Pull request closed without merging**
