### PR TITLE
Uniread

### PR DESCRIPTION
**Pull request by nemanjan00**

### CODE REVIEW

**Comment by jneidel** [comment]
Unusable due to https://github.com/nemanjan00/uniread/issues/24

**Comment by nemanjan00** [comment]
Are you experiencing that same problem?

**Comment by jneidel** [comment]
@nemanjan00 Yeah, that's why I referenced it.

**Comment by nemanjan00** [comment]
That is weird, I know a lot of people using it and it works just fine for them. 

What is your npm version? Do you have git installed? 
Node version? Windows or Linux?

**Comment by jneidel** [comment]
@nemanjan00:

> What is your npm/node version

latest (6.10.0/v11.15.0)

> Do you have git installed?

Of course

> Windows or Linux?

Linux. And it works neither on my Manjaro nor my Arch machine.

**Comment by nemanjan00** [comment]
Can you try yarn or npm without sudo?

**Comment by jneidel** [comment]
> Can you try yarn or npm without sudo?

On linux, if you install node from the package manager, using npm globally requires sudo as packages are installed for the whole system (/usr/lib and /usr/bin). From a security perspective this is as intended. You can get around that by installing global packages in your home dir, [as described here](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally), which I don't want to do because it adds unnecessary overhead.

That would fix the problem with this package.
Another option would be not to use a git repo as a dependency.

**Pull request closed without merging**
