### PR TITLE
Add flog

### PR DESCRIPTION
**Pull request by mingrammer**
#### New App Submission

**App name:** flog

**Repo or homepage link:** https://github.com/mingrammer/flog

**Description:** flog is a fake log generator for common log formats such as apache-common, apache error and RFC3164 syslog.

**Why you think it's awesome:** It is useful for testing some tasks which require log data like amazon kinesis log stream test.

### CODE REVIEW

**Comment by sjclayton** [comment]
This may be better suited to go under **Utilities** or **Development**

It doesn't manipulate existing data, it generates new fake log data.... so I don't think it should be under **Data Manipulation**

**Comment by mingrammer** [comment]
I moved the flog under the `Utilities` section

**Comment by jneidel** [comment]
@mingrammer What do you think about moving it into **Devops**?

**Comment by mingrammer** [comment]
Hm, It's a bit ambiguous to classify as DevOps

**Pull request merged**
